before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      # - linux # commented out to avoid the github.com/sqweek/dialog package issues
      - windows
      # - Darwin # commented out to avoid the cocoa package issues
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/hamzabow/co/cmd.Version={{.Version}}
      - -X github.com/hamzabow/co/cmd.Commit={{.Commit}}
      - -X github.com/hamzabow/co/cmd.Date={{.Date}}
    flags:
      - -trimpath
      - -tags=netgo
    main: ./main.go
    binary: co
    # No need for ignore section since darwin is not in goos list

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next+{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch