name: Development Build

on:
  push:
    branches:
      - staging
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Run GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0  # Disable CGO for better cross-compilation compatibility

      - name: Set date
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Create/Update Development Release
        uses: softprops/action-gh-release@v1
        with:
          name: Development Build
          tag_name: v0.0.0-dev.${{ steps.date.outputs.DATE }}
          files: dist/*
          prerelease: true
          body: |
            # Development Build
            
            This is an automated development build from commit ${{ github.sha }}
            
            This build is for testing purposes only and will be overwritten with each push to the main branch.
          generate_release_notes: false 